sh addGames.sh Rafa Pepe 1 2
sh addGames.sh Oriol Espada 3 1
sh addGames.sh Oriol Pepe 1 5
sh addGames.sh Rafa Pepe 1 2
sh addGames.sh Espada Rafa 0 2
sh addGames.sh Oriol Rafa 3 0
sh addGames.sh Jordi Espada 0 4
sh addGames.sh Espada Valenti 4 0
sh addGames.sh Espada Rafa 1 0
sh addGames.sh Rafa Oriol 1 1
sh addGames.sh Jordi Oriol 1 1
sh addGames.sh Rafa Pepe 0 0
sh addGames.sh Rafa Pepe 1 2
sh addGames.sh Oriol Pepe 1 0
sh addGames.sh Rafa Jordi 5 5
sh addGames.sh Oriol Espada 2 0
sh addGames.sh Oriol Jordi 2 3
sh addGames.sh Valenti Rafa 1 4
sh addGames.sh Valenti Oriol 0 1
sh addGames.sh Pepe Quique 3 1
sh addGames.sh Rafa Quique 2 3
sh addGames.sh Pepe Quique 1 0
sh addGames.sh Pepe Quique 2 0
sh addGames.sh Pepe Quique 3 2
sh addGames.sh Pepe Espada 1 0
sh addGames.sh Pepe Quique 1 2
sh addGames.sh Joan Oriol 0 1
sh addGames.sh Joan Oriol 0 0
sh addGames.sh Joan Oriol 1 2
sh addGames.sh Joan Oriol 5 0
sh addGames.sh Joan Oriol 1 0
sh addGames.sh Jordi Espada 1 1
sh addGames.sh Seb Oriol 0 0
sh addGames.sh Espada Pepe 2 3
sh addGames.sh Jordi Pepe 1 3
sh addGames.sh Espada Jordi 1 7
sh addGames.sh Jordi Espada 1 1
sh addGames.sh Jordi Espada 2 0
sh addGames.sh Jordi Espada 1 2
sh addGames.sh Jordi Seb 1 2
sh addGames.sh Jordi Seb 3 4
sh addGames.sh Jordi Seb 2 2
sh addGames.sh Pepe Valenti 4 0
sh addGames.sh Pepe Jordi 0 0
sh addGames.sh Pepe Jordi 4 0
sh addGames.sh Espada Oriol 1 1
sh addGames.sh Espada Oriol 0 0
sh addGames.sh Espada Oriol 3 1
sh addGames.sh Jordi Valenti 2 0
sh addGames.sh Jordi Rafa 3 2
sh addGames.sh Jordi Rafa 3 0
sh addGames.sh Jordi Pepe 2 0
sh addGames.sh Pepe Rafa 2 0
sh addGames.sh Mickey Pepe 1 5
sh addGames.sh Mickey Pepe 1 3
sh addGames.sh Jordi Oriol 0 1
sh addGames.sh Pepe Oriol 2 0
sh addGames.sh Jordi Rafa 2 2
sh addGames.sh Espada Oriol 1 2
sh addGames.sh Jordi Oriol 1 1
sh addGames.sh Espada Oriol 1 0
sh addGames.sh Espada Jordi 1 0
sh addGames.sh Mickey Jordi 1 1
sh addGames.sh Mickey Jordi 1 2
sh addGames.sh Mickey Jordi 3 2
sh addGames.sh Pepe Mickey 0 0
sh addGames.sh Pepe Mickey 2 1
